// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using esyasoft.mobility.CHRGUP.service.ocpp.Data;

#nullable disable

namespace esyasoft.mobility.CHRGUP.service.ocpp.Migrations
{
    [DbContext(typeof(OcppDbContext))]
    partial class OcppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("esyasoft.mobility.CHRGUP.service.ocpp.Data.OcppCharger", b =>
                {
                    b.Property<string>("ChargerId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChargerId");

                    b.ToTable("Chargers");
                });
#pragma warning restore 612, 618
        }
    }
}
